name: Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: install roblox-ts
        run: npm i -g roblox-ts
      - name: install local npm packages
        run: npm i --production=false
      - name: compile typescript code
        run: rbxtsc --type=model
      - name: install foreman
        uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: install foreman packages (rojo, run-in-roblox)
        run: foreman install
      - name: run rojo build
        run: rojo build -o ./finite-state-machine-${{ steps.package-version.outputs.current-version }}.rbxmx
      - name: create-release
        uses: actions/create-release@latest
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.package-version.outputs.current-version }}
          tag_name: ${{ steps.package-version.outputs.current-version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload rbxmx file to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./finite-state-machine-${{ steps.package-version.outputs.current-version }}.rbxmx
          asset_name: finite-state-machine-${{ steps.package-version.outputs.current-version }}.rbxmx
          asset_content_type: form
      - name: upload rbxmx file to Roblox
        run: |
          cd ./scripts
          python upload_model.py -a ${{ secrets.ASSET_ID }} -f ../finite-state-machine-${{ steps.package-version.outputs.current-version }}.rbxmx -r ${{ secrets.UPLOADER_BOT_ROBLOSECURITY }}
          cd ..
      - name: prepare wally package contents
        run: |
          mkdir -p ~/temp/finite-state-machine
          cp -r ./{include,out} ~/temp/finite-state-machine/
          cp ./{CHANGELOG.md,LICENSE,README.md,wally.lock,wally.toml} ~/temp/finite-state-machine/
          cp ./luau-model.project.json ~/temp/finite-state-machine/default.project.json
          mkdir ~/temp/finite-state-machine/node_modules
          cp -r ./node_modules/@rbxts ~/temp/finite-state-machine/node_modules/
      - name: prepare wally auth
        run: |
          mkdir ~/.wally
          echo -e '${{ secrets.WALLY_AUTH }}' > ~/.wally/auth.toml
      - name: publish wally package
        run: wally publish --project-path ~/temp/finite-state-machine/
