name: Release

on: [workflow_dispatch]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: install roblox-ts
        run: npm i -g roblox-ts
      - name: install local npm packages
        run: npm i --production=false
      - name: compile typescript code
        run: rbxtsc --type=model
      - name: install foreman
        uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: install foreman packages (rojo, run-in-roblox)
        run: foreman install
      - name: run rojo build
        run: rojo build -o ./finite-state-machine-${{ steps.package-version.outputs.current-version }}.rbxlx
      - name: create-release
        uses: actions/create-release@latest
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.package-version.outputs.current-version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload rbxmx file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./finite-state-machine-${{ steps.package-version.outputs.current-version }}.rbxlx
          asset_name: finite-state-machine-${{ steps.package-version.outputs.current-version }}.rbxlx